### ISSUE TITLE
TypeError: sql.query is not a function

### ISSUE THREAD

**Issue by JeeIn-Shin** [JeeIn-Shin/codeReview#2]
### **문제가 되는 코드**
```
const sql = require("../config/database.js");

const User = function (user_setting) {
    this.student_id = user_setting.student_id;
    this.password = user_setting.password;
    this.name = user_setting.name;
    this.email = user_setting.email;
    this.nickname = user_setting.nickname;
};

//사용자 회원가입
//student id, email, nickname UQ
User.create = (newUser, result) => {
    sql.query("INSERT INTO user SET ?", newUser, (err, res) => {
        if (err) {
            console.log("error: ", err);
            result(err, null);
            return;
        }
        console.log("created user: ", { id: res.insertId, ...newUser });
        result(null, { id: res.insertId, ...newUser });
    });
};

User.get_specific_user = (studentID, result) =>{
    sql.query(`SELECT * FROM user WHERE student_id likes '${studentID}'`, (err, res)=>{
        if(err){
            console.log("error: ", err);
            result(err, null);
            return;
        }

        console.log("user: ", res);
        result(null, res);
    });
};


module.exports = User;
```

**POSTMAN 실행결과**
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>TypeError: sql.query is not a function<br> &nbsp; &nbsp;at User.get_specific_user (F:\Project\codeReview\model\user.js:26:9)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (F:\Project\codeReview\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (F:\Project\codeReview\node_modules\express\lib\router\route.js:144:13)<br> &nbsp; &nbsp;at Route.dispatch (F:\Project\codeReview\node_modules\express\lib\router\route.js:114:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (F:\Project\codeReview\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at F:\Project\codeReview\node_modules\express\lib\router\index.js:284:15<br> &nbsp; &nbsp;at Function.process_params (F:\Project\codeReview\node_modules\express\lib\router\index.js:346:12)<br> &nbsp; &nbsp;at next (F:\Project\codeReview\node_modules\express\lib\router\index.js:280:10)<br> &nbsp; &nbsp;at urlencodedParser (F:\Project\codeReview\node_modules\body-parser\lib\types\urlencoded.js:100:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (F:\Project\codeReview\node_modules\express\lib\router\layer.js:95:5)</pre>
</body>

</html>

**Comment by JeeIn-Shin** [comment]
해결, 

sql.init().query() 형태로 작성해야함
